version: '3'

services:

    # PHP Service
    php:
        build:
            context: .docker/php
            dockerfile: Dockerfile
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached
        container_name: app
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        environment:
            - SERVICE_NAME=app
            - SERVICE_TAGS=dev
        networks:
            - app-network

    # Nginx Service
    nginx:
        image: nginx:alpine3.18-slim
        restart: unless-stopped
        tty: true
        ports:
            - 8080:80
        volumes:
            - ./:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
        container_name: web-server
        networks:
            - app-network

    # MySQL Service
    db:
        image: mysql:8.1
        restart: unless-stopped
        tty: true
        container_name: db
        ports:
            - 3306:3306
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/db/backups:/var/backups
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - SERVICE_NAME=mysql
            - SERVICE_TAGS=dev
        networks:
            - app-network

# Docker networks
networks:
    app-network:
        driver: bridge
